name: sign_in
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-382.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  shared_preferences: ^2.0.6
  image_picker: ^0.8.7
  firebase_storage: ^11.1.2
  cloud_firestore: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.2



flutter:

  uses-material-design: true

  assets:
   - images/

  fonts:
    - family: Pacifico
      fonts:
       - asset: fonts/Pacifico-Regular.ttf
    - family: Urbanist
      fonts:
        - asset: fonts/urbanist-Regular.ttf
    - family: Urbanist Pro
      fonts:
        - asset: fonts/urbanist-Bold.ttf